### PR TITLE
Update mingw extra-cmake-modules to 5.76.0

### PR DESCRIPTION
**Pull request by maxrd2**
Have updated all mingw KF5 packages in AUR to 5.76.0.
Can you update it there or orphan it and I'll do it.

cheers

BTW Have made some build scripts to create arch packages on openSUSE build system.
eg. https://build.opensuse.org/package/show/home:maxrd2/pocketsphinx
What do you think if we create repo and put all mingw PKGBUILDs in one repo there. You are building all mingw-qt5 packages here, I do the same here https://github.com/maxrd2/arch-repo/releases.
That way we could share effort and all packages would be built in clean chroot on OBS.

### CODE REVIEW

**Comment by Martchus** [comment]
I'm aware that it is possible to build Arch packages via OBS - but building packages is not the main effort. So using OBS can only help to some extend. However, it comes with drawbacks which so far led me to avoid using it for Arch Linux packaging:

* The main effort is the development of the PKGBUILDs itself and testing whether the resulting packages actually work. For that I'd like to stick to my own build scripts which provide a better compromise between automation and the possibility to do things manually when required, e.g. sometimes I'd just like to jump into the chroot after a failure to try out things manually.
* There's no good retention of the history. It doesn't use Git for versioning (I'm aware that there are attempts to do so). It also doesn't provide the history of previous build logs and old packages (at least not if you simply setup a home project). However, these are sometimes useful to investigate problems, e.g. to find out what has changed.
* Just setting up an OBS project likely doesn't give you a good staging/testing workflow. In practice I sometimes like to rebuild packages against Arch Linux staging or testing repository and I also like to be able to have a `-staging` and `-testing` repository myself so updates of multiple packages can be done in a consistent manner. I also have an `-experimental` repo I'm using during development to avoid disturbing the other repositories with my WIP packages. For these workflows to work efficiently I have helpers to move packages between repositories conveniently. I'm not aware that it is possible to move packages around between different subprojects of a home project on OBS.
* I'm also not sure how well OBS handles things like a GCC or CRT update. I hope it wouldn't rebuild all packages due to that unless it is really required because that time consuming task would possibly block building packages you're actually waiting for. But if it doesn't rebuild everything in these cases, I'm wondering how well it can detect necessary rebuilds. My build scripts so far can at least detect necessary rebuilds semi-automatically when the DLL name (or SO name for regular Linux packages) changes.
* I'm using OBS to build openSUSE and Fedora packages and it is sometimes just annoying to wait for packages to start building or to be published there when you locally have a server on your desk which would be free to do the task. I  want to be able to utilize my own hardware.
* I'd like to keep it simple. That's why I've chosen Arch Linux in the first place. OBS is a complex piece of software and frankly, it feels needlessly complicated for the task at hand. So far I use some simple bash scripts and a more sophisticated but yet not needlessly complicated "[build service](https://martchus.no-ip.biz/buildservice)" for bigger rebuilds. It also feels needless to involve a different distribution than Arch Linux for building Arch Linux packages. I'd like if things are self-contained.

---

> all packages would be built in clean chroot

I'd also like to note that all packages on my binary repository are already built in a clean chroot as well (using the official `makechrootpkg`).

---

Thanks for updating all the KDE packages within the AUR. I'll also add them back to my binary repository because they might become useful to me as well. (I removed them at some point because a rebuild of all mingw-w64 packages was required but the packages were outdated back then.)

**Comment by Martchus** [comment]
> I'll also add them back to my binary repository because they might become useful to me as well.

Some packages are still missing because `mingw-w64-libxslt` needed to be updated first.

**Comment by maxrd2** [comment]
I understand what you are saying, first time i've tried OBS I was using web interface and was annoyed by waits and difficulty of editing scripts and debugging builds.

Though OBS has command line tool osc which is based on subversion (so it does have detailed history retention) also osc can be used to test builds in local chroot on local system, and you can easily jump into chroot and debug builds, edit, build manually etc etc.
I suppose you haven't tried using osc tool (https://aur.archlinux.org/packages/osc/).

Why I suggested this is because I've been using custom build scripts too and until i found out this they were simplest/quickest/easiest thing to use and debug. With OBS/osc I've setup and tested builds for all current versions of Debian, Ubuntu, OpenSUSE and Arch in few hours.
Creating build script for single distribution on other online services (launchpad, travis) took well over a day and included a lot of trial and error and waiting for builds to finish.

Anyways.. After trying osc I liked how it smartly it uses caching for both download and package installation, and it did reduce test time and build time in local chroots.

Regarding upstream binary dependency updates, I believe you have to manually update pkgrel and push changed PKGBUILD in order for it to recompile. Don't think it will do that automatically for you.

I completely understand if you prefer to continue using what you are using now. I just thought it might be beneficial for all of us that are using mingw dependencies from AUR to put them into build service and just download binaries through pacman when they are needed (OBS handles arch repo creation too e.g. https://download.opensuse.org/repositories/home:/maxrd2/Arch/x86_64/).

**Comment by Martchus** [comment]
I'm already using osc for creating openSUSE, Fedora and AppImage packages of my own projects.

Maybe there are indeed better debugging options than I'm currently aware of. I also know that osc has its own versioning but it seems very inaccessible to me (compared to Git). Additionally, I'm also talking about the binary package and logfiles.

> I just thought it might be beneficial for all of us that are using mingw dependencies from AUR to put them into build service and just download binaries through pacman when they are needed.

One of the things I like about my current approach is that I can add packages from different sources to my repository. So to save build time I could actually just copy over packages from your repository.

Note that the lack of the staging and testing workflow is still problematic for my use cases. For instance, currently I have already versions of sphinxbase, pocketsphinx, the mentioned osc and a few other packages in my `ownstuff-testing` repo. These packages are built against python 3.9 which is already in the official testing repo. When python 3.9 lands in the regular repos I'll simply move the packages over to my regular `ownstuff` repo. That's important to me because otherwise I couldn't use these packages on my Arch systems which have testing repos enabled.

**Pull request merged**
