### PR TITLE
Apply patch only once

### PR DESCRIPTION
**Pull request by hipersayanX**
Apply patch only once and don't stop package build if the patch fail, specially when resuming from a previous build. And makepkg will inform if the patch is broken anyways.

### CODE REVIEW

**Comment by Martchus** [comment]
Makes sense for resuming a build (I usually just skip the entire prepare step in this case). I'll sync the other variants and update the AUR tomorrow.

**Comment by Martchus** [comment]
>And makepkg will inform if the patch is broken anyways.

Wait, how will `makepkg` be able to do that with the ` || true` (which I overlooked before merging the changes)?

**Comment by hipersayanX** [comment]
If I don't add the || true the _prepare_ step will fail after:

```
which already exists!  Skipping patch.
1 out of 1 hunk ignored
```

**Comment by Martchus** [comment]
Mh... yes. But using ` || true` is not common (eg. see the [regular package](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/qt5-base)). I suppose because you usually just use `--noprepare` to prevent that kind of failure.

**Comment by hipersayanX** [comment]
Oh get it, i normally run makepkg as is.

**Pull request merged**
