### PR TITLE
Add dependency on gcc-libs to c++utilities

### PR DESCRIPTION
**Pull request by Arvedui**
c++utilities has a runtime dependency on gcc-libs which must be declared.

### CODE REVIEW

**Comment by Martchus** [comment]
The base package which defines a minimum Arch Linux installation depends on it already. However, it seems to be indeed practice to list it nevertheless.

Can you update the Git package as well (for consistency)?

**Comment by Arvedui** [comment]
Sure

qtutilities and syncthingtray are also missing some dependencies. Both need gcc-libs as well and synchtingtray should depend on hicolor-icon-theme.
May I add them here as well or should i open a new PR for them?

**Comment by Martchus** [comment]
I guess it is sufficient that qtutilities already depends on c++utilities which will always depend on gcc-libs.

Syncthing Tray should work without any icon theme installed because it provides fallback icons for buttons which only have an icon (and no text). That's actually just to cover the case that the icon theme is missing certain icons but it should also cover the case when there's no icon theme at all.

**Comment by Arvedui** [comment]
> I guess it is sufficient that qtutilities already depends on c++utilities which will always depend on gcc-libs.

I strongly disagree with that. In my opinion one must no rely on transitive dependencies no matter how obvious they may seem. 

> 
> Syncthing Tray should work without any icon theme installed because it provides fallback icons for buttons which only have an icon (and no text). That's actually just to cover the case that the icon theme is missing certain icons but it should also cover the case when there's no icon theme at all.

Alright.

**Comment by Martchus** [comment]
The [Wiki](https://wiki.archlinux.org/index.php/PKGBUILD#depends) says "In some cases this is not necessary and may or may not be listed" and a lot of official packages like qt5-base, filezilla and ogre do not explicitly depend on `gcc-libs` although these projects definitely make direct use of `gcc-libs`.

But you can definitely already add `gcc-libs` to `c++utilities-git`. Then I'll merge the PR and update the AUR.

**Comment by Arvedui** [comment]
I still disagree. Everything that a binary directly depends on should be declared, unfortunately even many arch devs don't do this right.

But alright. I added it do c++utilities-git.

**Comment by Martchus** [comment]
I guess it would just become a little bit tedious to add the dependency to almost every package considering there's almost no practical benefit. I'd consider it one of the ways where Arch tries to keep it simple.

Note that packaging systems of other distributions are more sophisticated and do it exactly like you suggest. At least under openSUSE library dependencies are tracked on soname-level. But there it is not tedious because these dependencies are detected and added automatically. I would argue that such an automatic detection would make sense for Arch as well (instead of now trying to fix packages one-by-one). I've recently developed a build system for Arch which does exactly that to know when I need to rebuild packages in my custom repo so it would be doable. (Also works for mingw-w64 packages and Android packages.) Note that also the official Arch devs do some external tracking on soname level to know which packages need to be rebuilt so they have it basically covered as well - although the dependency tracking doesn't happen on PKGBUILD level.

**Pull request merged**
