### PR TITLE
fix duplicate `kde+` suffix in version

### PR DESCRIPTION
**Pull request by BenSYZ**
modify the definition of `_basever` from `_basever=$pkgver` to `_basever=${pkgver%%+*}`

### CODE REVIEW

**Comment by BenSYZ** [comment]
The script I use:

```zsh
for f in $(grep -r -l '^_basever=\$pkgver$' -l );do
    if grep 'basever+kde+r' $f >/dev/null;then
        sed -i 's/^_basever=\$pkgver$/_basever=\${pkgver%%+*}/' $f
    fi
done
```

**Comment by Martchus** [comment]
What is the problem you're trying to fix here?

The version of the regular qt5-base package is `5.15.11+kde+r138-1` and the version mingw-w64-qt5-base (in my binary repository) is `5.15.11+kde+r135-1`. So both are in-line with each other. I've also checked a few modules and they are also in-line with the regular package. So I honestly don't see a problem here.

**Comment by BenSYZ** [comment]
Sorry for not describing the problem. And thanks for your patient reply.

Yes, the problem was first found with AUR helper when I install `mingw-w64-qt5-serialport`. Putting the AUR Helper aside, there is a small problem when build with `makepkg`. `makepkg -si` works fine when the repository is clean, and after the installation, the origin PKGBUILD file is changed, the `pkgver` becomes `5.15.11+kde+r0`. At this time, If I run `makepkg` without restore the changes to PKGBUILD, the version become wrong: version suffix will add an extra `+kde-r0`. Each time I run `makepkg`, the `+kde+r` will append. Take `mingw-w64-qt5-serialport` as example, when I run `makepkg -si` once, the version is `5.15.11+kde+r0`. When I run `makepkg -si` for the second time, the version becomes `5.15.11+kde+r0+kde+r`. This is a little messy.

Besides, the problem for AUR help may comes from that it run `makepkg` multiple times for one install.

Maybe that run `makepkg` without restoring the repository is a bad idea. If so, I would close the pr.

**Comment by Martchus** [comment]
That makes sense, I've merged the changes and will update the AUR.

**Pull request merged**
