### PR TITLE
Build python bindings for pocketsphinx

### PR DESCRIPTION
**Pull request by micwoj92**

### CODE REVIEW

**Comment by Martchus** [comment]
I gave it a test build and it looks good. So thanks, I've pushed your changes to the AUR.

**Comment by micwoj92** [comment]
Thanks for quick merge

**Comment by micwoj92** [comment]
The last namcap complaint is that the license field contains 3, but it is actually installed as 1 file. Do you think it makes sense to split or nah?

**Comment by Martchus** [comment]
If upstream provides their licenses only as combined file I think this is good enough.

**Pull request merged**
